/**
 * Copyright 2009 Jason Hewitt
 */
package org.jaspa.eternity2.tile;

import java.util.HashMap;

/**
 * class contains the constants used for the TileIdSets
 * Each single tile is given one of the TileId sets which contains a single
 * element.
 */
public class TileIdConst {

    private static final HashMap<Integer, TileIdSet> registry = new HashMap<Integer, TileIdSet>();

    public static final TileIdSet T001 = createAndRegister(1);
    public static final TileIdSet T002 = createAndRegister(2);
    public static final TileIdSet T003 = createAndRegister(3);
    public static final TileIdSet T004 = createAndRegister(4);
    public static final TileIdSet T005 = createAndRegister(5);
    public static final TileIdSet T006 = createAndRegister(6);
    public static final TileIdSet T007 = createAndRegister(7);
    public static final TileIdSet T008 = createAndRegister(8);
    public static final TileIdSet T009 = createAndRegister(9);
    public static final TileIdSet T010 = createAndRegister(10);
    public static final TileIdSet T011 = createAndRegister(11);
    public static final TileIdSet T012 = createAndRegister(12);
    public static final TileIdSet T013 = createAndRegister(13);
    public static final TileIdSet T014 = createAndRegister(14);
    public static final TileIdSet T015 = createAndRegister(15);
    public static final TileIdSet T016 = createAndRegister(16);
    public static final TileIdSet T017 = createAndRegister(17);
    public static final TileIdSet T018 = createAndRegister(18);
    public static final TileIdSet T019 = createAndRegister(19);
    public static final TileIdSet T020 = createAndRegister(20);
    public static final TileIdSet T021 = createAndRegister(21);
    public static final TileIdSet T022 = createAndRegister(22);
    public static final TileIdSet T023 = createAndRegister(23);
    public static final TileIdSet T024 = createAndRegister(24);
    public static final TileIdSet T025 = createAndRegister(25);
    public static final TileIdSet T026 = createAndRegister(26);
    public static final TileIdSet T027 = createAndRegister(27);
    public static final TileIdSet T028 = createAndRegister(28);
    public static final TileIdSet T029 = createAndRegister(29);
    public static final TileIdSet T030 = createAndRegister(30);
    public static final TileIdSet T031 = createAndRegister(31);
    public static final TileIdSet T032 = createAndRegister(32);
    public static final TileIdSet T033 = createAndRegister(33);
    public static final TileIdSet T034 = createAndRegister(34);
    public static final TileIdSet T035 = createAndRegister(35);
    public static final TileIdSet T036 = createAndRegister(36);
    public static final TileIdSet T037 = createAndRegister(37);
    public static final TileIdSet T038 = createAndRegister(38);
    public static final TileIdSet T039 = createAndRegister(39);
    public static final TileIdSet T040 = createAndRegister(40);
    public static final TileIdSet T041 = createAndRegister(41);
    public static final TileIdSet T042 = createAndRegister(42);
    public static final TileIdSet T043 = createAndRegister(43);
    public static final TileIdSet T044 = createAndRegister(44);
    public static final TileIdSet T045 = createAndRegister(45);
    public static final TileIdSet T046 = createAndRegister(46);
    public static final TileIdSet T047 = createAndRegister(47);
    public static final TileIdSet T048 = createAndRegister(48);
    public static final TileIdSet T049 = createAndRegister(49);
    public static final TileIdSet T050 = createAndRegister(50);
    public static final TileIdSet T051 = createAndRegister(51);
    public static final TileIdSet T052 = createAndRegister(52);
    public static final TileIdSet T053 = createAndRegister(53);
    public static final TileIdSet T054 = createAndRegister(54);
    public static final TileIdSet T055 = createAndRegister(55);
    public static final TileIdSet T056 = createAndRegister(56);
    public static final TileIdSet T057 = createAndRegister(57);
    public static final TileIdSet T058 = createAndRegister(58);
    public static final TileIdSet T059 = createAndRegister(59);
    public static final TileIdSet T060 = createAndRegister(60);
    public static final TileIdSet T061 = createAndRegister(61);
    public static final TileIdSet T062 = createAndRegister(62);
    public static final TileIdSet T063 = createAndRegister(63);
    public static final TileIdSet T064 = createAndRegister(64);
    public static final TileIdSet T065 = createAndRegister(65);
    public static final TileIdSet T066 = createAndRegister(66);
    public static final TileIdSet T067 = createAndRegister(67);
    public static final TileIdSet T068 = createAndRegister(68);
    public static final TileIdSet T069 = createAndRegister(69);
    public static final TileIdSet T070 = createAndRegister(70);
    public static final TileIdSet T071 = createAndRegister(71);
    public static final TileIdSet T072 = createAndRegister(72);
    public static final TileIdSet T073 = createAndRegister(73);
    public static final TileIdSet T074 = createAndRegister(74);
    public static final TileIdSet T075 = createAndRegister(75);
    public static final TileIdSet T076 = createAndRegister(76);
    public static final TileIdSet T077 = createAndRegister(77);
    public static final TileIdSet T078 = createAndRegister(78);
    public static final TileIdSet T079 = createAndRegister(79);
    public static final TileIdSet T080 = createAndRegister(80);
    public static final TileIdSet T081 = createAndRegister(81);
    public static final TileIdSet T082 = createAndRegister(82);
    public static final TileIdSet T083 = createAndRegister(83);
    public static final TileIdSet T084 = createAndRegister(84);
    public static final TileIdSet T085 = createAndRegister(85);
    public static final TileIdSet T086 = createAndRegister(86);
    public static final TileIdSet T087 = createAndRegister(87);
    public static final TileIdSet T088 = createAndRegister(88);
    public static final TileIdSet T089 = createAndRegister(89);
    public static final TileIdSet T090 = createAndRegister(90);
    public static final TileIdSet T091 = createAndRegister(91);
    public static final TileIdSet T092 = createAndRegister(92);
    public static final TileIdSet T093 = createAndRegister(93);
    public static final TileIdSet T094 = createAndRegister(94);
    public static final TileIdSet T095 = createAndRegister(95);
    public static final TileIdSet T096 = createAndRegister(96);
    public static final TileIdSet T097 = createAndRegister(97);
    public static final TileIdSet T098 = createAndRegister(98);
    public static final TileIdSet T099 = createAndRegister(99);
    public static final TileIdSet T100 = createAndRegister(100);
    public static final TileIdSet T101 = createAndRegister(101);
    public static final TileIdSet T102 = createAndRegister(102);
    public static final TileIdSet T103 = createAndRegister(103);
    public static final TileIdSet T104 = createAndRegister(104);
    public static final TileIdSet T105 = createAndRegister(105);
    public static final TileIdSet T106 = createAndRegister(106);
    public static final TileIdSet T107 = createAndRegister(107);
    public static final TileIdSet T108 = createAndRegister(108);
    public static final TileIdSet T109 = createAndRegister(109);
    public static final TileIdSet T110 = createAndRegister(110);
    public static final TileIdSet T111 = createAndRegister(111);
    public static final TileIdSet T112 = createAndRegister(112);
    public static final TileIdSet T113 = createAndRegister(113);
    public static final TileIdSet T114 = createAndRegister(114);
    public static final TileIdSet T115 = createAndRegister(115);
    public static final TileIdSet T116 = createAndRegister(116);
    public static final TileIdSet T117 = createAndRegister(117);
    public static final TileIdSet T118 = createAndRegister(118);
    public static final TileIdSet T119 = createAndRegister(119);
    public static final TileIdSet T120 = createAndRegister(120);
    public static final TileIdSet T121 = createAndRegister(121);
    public static final TileIdSet T122 = createAndRegister(122);
    public static final TileIdSet T123 = createAndRegister(123);
    public static final TileIdSet T124 = createAndRegister(124);
    public static final TileIdSet T125 = createAndRegister(125);
    public static final TileIdSet T126 = createAndRegister(126);
    public static final TileIdSet T127 = createAndRegister(127);
    public static final TileIdSet T128 = createAndRegister(128);
    public static final TileIdSet T129 = createAndRegister(129);
    public static final TileIdSet T130 = createAndRegister(130);
    public static final TileIdSet T131 = createAndRegister(131);
    public static final TileIdSet T132 = createAndRegister(132);
    public static final TileIdSet T133 = createAndRegister(133);
    public static final TileIdSet T134 = createAndRegister(134);
    public static final TileIdSet T135 = createAndRegister(135);
    public static final TileIdSet T136 = createAndRegister(136);
    public static final TileIdSet T137 = createAndRegister(137);
    public static final TileIdSet T138 = createAndRegister(138);
    public static final TileIdSet T139 = createAndRegister(139);
    public static final TileIdSet T140 = createAndRegister(140);
    public static final TileIdSet T141 = createAndRegister(141);
    public static final TileIdSet T142 = createAndRegister(142);
    public static final TileIdSet T143 = createAndRegister(143);
    public static final TileIdSet T144 = createAndRegister(144);
    public static final TileIdSet T145 = createAndRegister(145);
    public static final TileIdSet T146 = createAndRegister(146);
    public static final TileIdSet T147 = createAndRegister(147);
    public static final TileIdSet T148 = createAndRegister(148);
    public static final TileIdSet T149 = createAndRegister(149);
    public static final TileIdSet T150 = createAndRegister(150);
    public static final TileIdSet T151 = createAndRegister(151);
    public static final TileIdSet T152 = createAndRegister(152);
    public static final TileIdSet T153 = createAndRegister(153);
    public static final TileIdSet T154 = createAndRegister(154);
    public static final TileIdSet T155 = createAndRegister(155);
    public static final TileIdSet T156 = createAndRegister(156);
    public static final TileIdSet T157 = createAndRegister(157);
    public static final TileIdSet T158 = createAndRegister(158);
    public static final TileIdSet T159 = createAndRegister(159);
    public static final TileIdSet T160 = createAndRegister(160);
    public static final TileIdSet T161 = createAndRegister(161);
    public static final TileIdSet T162 = createAndRegister(162);
    public static final TileIdSet T163 = createAndRegister(163);
    public static final TileIdSet T164 = createAndRegister(164);
    public static final TileIdSet T165 = createAndRegister(165);
    public static final TileIdSet T166 = createAndRegister(166);
    public static final TileIdSet T167 = createAndRegister(167);
    public static final TileIdSet T168 = createAndRegister(168);
    public static final TileIdSet T169 = createAndRegister(169);
    public static final TileIdSet T170 = createAndRegister(170);
    public static final TileIdSet T171 = createAndRegister(171);
    public static final TileIdSet T172 = createAndRegister(172);
    public static final TileIdSet T173 = createAndRegister(173);
    public static final TileIdSet T174 = createAndRegister(174);
    public static final TileIdSet T175 = createAndRegister(175);
    public static final TileIdSet T176 = createAndRegister(176);
    public static final TileIdSet T177 = createAndRegister(177);
    public static final TileIdSet T178 = createAndRegister(178);
    public static final TileIdSet T179 = createAndRegister(179);
    public static final TileIdSet T180 = createAndRegister(180);
    public static final TileIdSet T181 = createAndRegister(181);
    public static final TileIdSet T182 = createAndRegister(182);
    public static final TileIdSet T183 = createAndRegister(183);
    public static final TileIdSet T184 = createAndRegister(184);
    public static final TileIdSet T185 = createAndRegister(185);
    public static final TileIdSet T186 = createAndRegister(186);
    public static final TileIdSet T187 = createAndRegister(187);
    public static final TileIdSet T188 = createAndRegister(188);
    public static final TileIdSet T189 = createAndRegister(189);
    public static final TileIdSet T190 = createAndRegister(190);
    public static final TileIdSet T191 = createAndRegister(191);
    public static final TileIdSet T192 = createAndRegister(192);
    public static final TileIdSet T193 = createAndRegister(193);
    public static final TileIdSet T194 = createAndRegister(194);
    public static final TileIdSet T195 = createAndRegister(195);
    public static final TileIdSet T196 = createAndRegister(196);
    public static final TileIdSet T197 = createAndRegister(197);
    public static final TileIdSet T198 = createAndRegister(198);
    public static final TileIdSet T199 = createAndRegister(199);
    public static final TileIdSet T200 = createAndRegister(200);
    public static final TileIdSet T201 = createAndRegister(201);
    public static final TileIdSet T202 = createAndRegister(202);
    public static final TileIdSet T203 = createAndRegister(203);
    public static final TileIdSet T204 = createAndRegister(204);
    public static final TileIdSet T205 = createAndRegister(205);
    public static final TileIdSet T206 = createAndRegister(206);
    public static final TileIdSet T207 = createAndRegister(207);
    public static final TileIdSet T208 = createAndRegister(208);
    public static final TileIdSet T209 = createAndRegister(209);
    public static final TileIdSet T210 = createAndRegister(210);
    public static final TileIdSet T211 = createAndRegister(211);
    public static final TileIdSet T212 = createAndRegister(212);
    public static final TileIdSet T213 = createAndRegister(213);
    public static final TileIdSet T214 = createAndRegister(214);
    public static final TileIdSet T215 = createAndRegister(215);
    public static final TileIdSet T216 = createAndRegister(216);
    public static final TileIdSet T217 = createAndRegister(217);
    public static final TileIdSet T218 = createAndRegister(218);
    public static final TileIdSet T219 = createAndRegister(219);
    public static final TileIdSet T220 = createAndRegister(220);
    public static final TileIdSet T221 = createAndRegister(221);
    public static final TileIdSet T222 = createAndRegister(222);
    public static final TileIdSet T223 = createAndRegister(223);
    public static final TileIdSet T224 = createAndRegister(224);
    public static final TileIdSet T225 = createAndRegister(225);
    public static final TileIdSet T226 = createAndRegister(226);
    public static final TileIdSet T227 = createAndRegister(227);
    public static final TileIdSet T228 = createAndRegister(228);
    public static final TileIdSet T229 = createAndRegister(229);
    public static final TileIdSet T230 = createAndRegister(230);
    public static final TileIdSet T231 = createAndRegister(231);
    public static final TileIdSet T232 = createAndRegister(232);
    public static final TileIdSet T233 = createAndRegister(233);
    public static final TileIdSet T234 = createAndRegister(234);
    public static final TileIdSet T235 = createAndRegister(235);
    public static final TileIdSet T236 = createAndRegister(236);
    public static final TileIdSet T237 = createAndRegister(237);
    public static final TileIdSet T238 = createAndRegister(238);
    public static final TileIdSet T239 = createAndRegister(239);
    public static final TileIdSet T240 = createAndRegister(240);
    public static final TileIdSet T241 = createAndRegister(241);
    public static final TileIdSet T242 = createAndRegister(242);
    public static final TileIdSet T243 = createAndRegister(243);
    public static final TileIdSet T244 = createAndRegister(244);
    public static final TileIdSet T245 = createAndRegister(245);
    public static final TileIdSet T246 = createAndRegister(246);
    public static final TileIdSet T247 = createAndRegister(247);
    public static final TileIdSet T248 = createAndRegister(248);
    public static final TileIdSet T249 = createAndRegister(249);
    public static final TileIdSet T250 = createAndRegister(250);
    public static final TileIdSet T251 = createAndRegister(251);
    public static final TileIdSet T252 = createAndRegister(252);
    public static final TileIdSet T253 = createAndRegister(253);
    public static final TileIdSet T254 = createAndRegister(254);
    public static final TileIdSet T255 = createAndRegister(255);
    public static final TileIdSet T256 = createAndRegister(256);

    /**
     * finds the TileIdSet for a given name
     *
     * @param name The name of the TileIdSet to return
     * @return The TileIdSet with the given number
     */
    public static TileIdSet getTileIdSetFromName(String name) {
        int number = Integer.parseInt(name);
        TileIdSet result = registry.get(number);
        return result;
    }

    private static TileIdSet createAndRegister(int i) {
        TileIdSet tileIdSet = new TileIdSet(i);
        registry.put(i, tileIdSet);
        return tileIdSet;
    }

}
